# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable the Corne OLED Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y

# On macOS the BLE battery reporting packets can cause the computer to wakeup from sleep. To prevent this, the battery reporting service can be disabled by setting CONFIG_BT_BAS=n. This setting is independent of battery monitoring, for instance the battery level can still be indicated on a display.
# See https://zmk.dev/docs/config/battery#kconfig
CONFIG_BT_BAS=n

